"""OpenAPI YAML load / dump."""

from __future__ import annotations

import yaml

from md_drf_codegen.generator.openapi_generator import build_openapi_document
from md_drf_codegen.schema import ApiSpec
from md_drf_codegen.validator import validate_api_spec

OPENAPI_HEADER = (
    "# AUTO-GENERATED FILE.\n"
    "# Generated from a Markdown / ApiSpec YAML by md-drf-codegen.\n"
    "# OpenAPI 3.0 — import into Swagger Editor / Swagger UI.\n"
    "# Do not edit this file directly; edit the source Markdown instead.\n"
)


def dump_openapi_yaml(
    spec: ApiSpec,
    *,
    title: str | None = None,
    api_version: str = "1.0.0",
) -> str:
    validate_api_spec(spec)
    document = build_openapi_document(
        spec,
        title=title or _default_title(spec),
        api_version=api_version,
    )
    body = yaml.safe_dump(
        document,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
    )
    return OPENAPI_HEADER + body


def _default_title(spec: ApiSpec) -> str:
    if spec.apis:
        return spec.apis[0].name
    return "API"
