"""YAML load / dump for ApiSpec."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml
from pydantic import ValidationError

from md_drf_codegen.errors import SchemaValidationError
from md_drf_codegen.models import ApiSpec

YAML_HEADER = (
    "# AUTO-GENERATED FILE.\n"
    "# Generated from a Markdown API specification by md-drf-codegen.\n"
    "# Do not edit this file directly; edit the source Markdown instead.\n"
)


def api_spec_to_dict(spec: ApiSpec) -> dict[str, Any]:
    return spec.model_dump(mode="json", by_alias=True, exclude_none=True)


def dump_api_spec_yaml(spec: ApiSpec) -> str:
    data = api_spec_to_dict(spec)
    body = yaml.safe_dump(
        data,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
    )
    return YAML_HEADER + body


def write_api_spec_yaml(spec: ApiSpec, path: str | Path) -> Path:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(dump_api_spec_yaml(spec), encoding="utf-8")
    return output


def load_api_spec_yaml(path: str | Path) -> ApiSpec:
    source = Path(path)
    raw = source.read_text(encoding="utf-8")
    return parse_api_spec_yaml(raw, source_path=str(source))


def parse_api_spec_yaml(raw: str, *, source_path: str = "<memory>") -> ApiSpec:
    try:
        data = yaml.safe_load(raw)
    except yaml.YAMLError as exc:
        raise SchemaValidationError(
            f"Failed to parse YAML: {exc}",
            fix=f"Fix YAML syntax in {source_path}.",
        ) from exc

    if data is None:
        raise SchemaValidationError(
            "YAML document is empty.",
            fix=f"Provide a valid ApiSpec document in {source_path}.",
        )
    if not isinstance(data, dict):
        raise SchemaValidationError(
            "YAML root must be a mapping.",
            fix=f"Ensure {source_path} starts with version/title/apis/types keys.",
        )

    try:
        return ApiSpec.model_validate(data)
    except ValidationError as exc:
        details = "; ".join(
            f"{'.'.join(str(part) for part in err['loc'])}: {err['msg']}" for err in exc.errors()
        )
        raise SchemaValidationError(
            f"YAML failed Pydantic validation: {details}",
            fix=f"Fix the reported fields in {source_path}.",
        ) from exc
